@@ -5,6 +5,7 @@ nav:
        - File format: 'usage/file_format.md'
        - Using command line:
            - dnn_act: 'usage/cmd/dnn_act.md'
            - dnn_minstim: 'usage/cmd/dnn_minstim.md'
            - dnn_topstim: 'usage/cmd/dnn_topstim.md'
        - Using python lib:
            - extract_dnn_activation: 'usage/pylib/extract_dnn_activation.md'
    - API: 'API/TBD.md'
@@ -13,4 +14,4 @@ theme: readthedocs
markdown_extensions:
    - toc:
        permalink: "#"
        separator: "_"
        separator: "_"
